export type ProviderType = 'gemini' | 'groq' | 'ollama'

export interface AIOpponent {
  id: string
  name: string
  shortName: string
  elo: number
  playstyle: string
  provider: string
  description: string
  gradient: string
  iconName: string
  winRate: number
  free: boolean
  modelId: string
  providerType: ProviderType
  requiresSetup?: boolean
  setupNote?: string
}

export const AI_OPPONENTS: AIOpponent[] = [
  // ─── Google Gemini ────────────────────────────────────────────────────────
  {
    id: 'gemini-flash',
    name: 'Gemini 1.5 Flash',
    shortName: 'Gemini Flash',
    elo: 1800,
    playstyle: 'Positional / Balanced',
    provider: 'Google DeepMind',
    description: 'Fast and versatile. Gemini Flash balances speed with strategic depth.',
    gradient: 'from-blue-400 to-purple-500',
    iconName: 'psychology',
    winRate: 62,
    free: true,
    modelId: 'gemini-1.5-flash',
    providerType: 'gemini',
  },
  {
    id: 'gemini-pro',
    name: 'Gemini 1.5 Pro',
    shortName: 'Gemini Pro',
    elo: 2200,
    playstyle: 'Positional / Sharp',
    provider: 'Google DeepMind',
    description: "Google's most capable model. Plays a deep positional style with sharp tactical vision.",
    gradient: 'from-violet-500 to-indigo-600',
    iconName: 'psychology',
    winRate: 68,
    free: true,
    modelId: 'gemini-1.5-pro',
    providerType: 'gemini',
  },
  {
    id: 'gemini-2-flash',
    name: 'Gemini 2.0 Flash',
    shortName: 'Gemini 2.0',
    elo: 2600,
    playstyle: 'Aggressive / Tactical',
    provider: 'Google DeepMind',
    description: 'The latest generation. Combines brutal tactical play with long-term strategic planning.',
    gradient: 'from-emerald-400 to-cyan-500',
    iconName: 'smart_toy',
    winRate: 74,
    free: true,
    modelId: 'gemini-2.0-flash',
    providerType: 'gemini',
  },

  // ─── Groq (free API key required) ────────────────────────────────────────
  {
    id: 'groq-gpt-oss-120b',
    name: 'GPT-OSS 120B',
    shortName: 'GPT-OSS 120B',
    elo: 2400,
    playstyle: 'Deep / Strategic',
    provider: 'Groq (Free)',
    description: "OpenAI's flagship open-weight model with 120B parameters, hosted free on Groq's fast inference chips.",
    gradient: 'from-slate-400 to-gray-600',
    iconName: 'auto_awesome',
    winRate: 71,
    free: true,
    modelId: 'openai/gpt-4o',
    providerType: 'groq',
    requiresSetup: true,
    setupNote: 'Requires a free GROQ_API_KEY in .env.local — get one at console.groq.com',
  },
  {
    id: 'groq-gpt-oss-20b',
    name: 'GPT-OSS 20B',
    shortName: 'GPT-OSS 20B',
    elo: 2000,
    playstyle: 'Balanced / Tactical',
    provider: 'Groq (Free)',
    description: "OpenAI's efficient open-weight model. Fast, capable, and runs free on Groq hardware.",
    gradient: 'from-neutral-400 to-stone-600',
    iconName: 'auto_awesome',
    winRate: 66,
    free: true,
    modelId: 'openai/gpt-4o-mini',
    providerType: 'groq',
    requiresSetup: true,
    setupNote: 'Requires a free GROQ_API_KEY in .env.local — get one at console.groq.com',
  },
  {
    id: 'groq-llama3-70b',
    name: 'Llama 3.3 70B',
    shortName: 'Llama 3.3',
    elo: 1900,
    playstyle: 'Tactical / Aggressive',
    provider: 'Groq (Free)',
    description: "Meta's powerful open-source model hosted on Groq's blazing-fast inference chip. Free API key required.",
    gradient: 'from-orange-400 to-red-500',
    iconName: 'pets',
    winRate: 64,
    free: true,
    modelId: 'llama-3.3-70b-versatile',
    providerType: 'groq',
    requiresSetup: true,
    setupNote: 'Requires a free GROQ_API_KEY in .env.local — get one at console.groq.com',
  },
  {
    id: 'groq-llama4-scout',
    name: 'Llama 4 Scout',
    shortName: 'Llama 4 Scout',
    elo: 2100,
    playstyle: 'Aggressive / Tactical',
    provider: 'Groq (Free)',
    description: "Meta's newest Llama 4 generation — a 17B expert model with 16 specialists for sharp tactical play.",
    gradient: 'from-amber-400 to-orange-600',
    iconName: 'search',
    winRate: 67,
    free: true,
    modelId: 'meta-llama/llama-4-scout-17b-16e-instruct',
    providerType: 'groq',
    requiresSetup: true,
    setupNote: 'Requires a free GROQ_API_KEY in .env.local — get one at console.groq.com',
  },
  {
    id: 'groq-qwen3-32b',
    name: 'Qwen3 32B',
    shortName: 'Qwen3',
    elo: 2000,
    playstyle: 'Positional / Precise',
    provider: 'Groq (Free)',
    description: "Alibaba's Qwen3 with 32B parameters. Known for precise calculation and positional understanding.",
    gradient: 'from-blue-500 to-indigo-700',
    iconName: 'language',
    winRate: 65,
    free: true,
    modelId: 'qwen/qwen3-32b',
    providerType: 'groq',
    requiresSetup: true,
    setupNote: 'Requires a free GROQ_API_KEY in .env.local — get one at console.groq.com',
  },
  {
    id: 'groq-mixtral',
    name: 'Mixtral 8x7B',
    shortName: 'Mixtral',
    elo: 1700,
    playstyle: 'Balanced / Positional',
    provider: 'Groq (Free)',
    description: "Mistral's mixture-of-experts model. Solid positional understanding with fast response times.",
    gradient: 'from-pink-400 to-rose-600',
    iconName: 'hub',
    winRate: 58,
    free: true,
    modelId: 'mixtral-8x7b-32768',
    providerType: 'groq',
    requiresSetup: true,
    setupNote: 'Requires a free GROQ_API_KEY in .env.local — get one at console.groq.com',
  },

  // ─── Ollama (local, truly free) ───────────────────────────────────────────
  {
    id: 'ollama-llama3',
    name: 'Llama 3 (Local)',
    shortName: 'Local Llama',
    elo: 1600,
    playstyle: 'Balanced',
    provider: 'Ollama (Local)',
    description: "Runs 100% on your machine. No API key, no internet needed. Requires Ollama + 'ollama pull llama3'.",
    gradient: 'from-lime-400 to-green-600',
    iconName: 'computer',
    winRate: 55,
    free: true,
    modelId: 'llama3',
    providerType: 'ollama',
    requiresSetup: true,
    setupNote: 'Requires Ollama running locally at localhost:11434 with llama3 model pulled.',
  },
  {
    id: 'ollama-mistral',
    name: 'Mistral (Local)',
    shortName: 'Local Mistral',
    elo: 1500,
    playstyle: 'Solid / Defensive',
    provider: 'Ollama (Local)',
    description: "Mistral 7B running on your own hardware. Efficient and privacy-preserving chess AI.",
    gradient: 'from-teal-400 to-cyan-600',
    iconName: 'computer',
    winRate: 52,
    free: true,
    modelId: 'mistral',
    providerType: 'ollama',
    requiresSetup: true,
    setupNote: "Requires Ollama running locally at localhost:11434 with mistral model pulled.",
  },
]
