/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#11140d',
        'surface': '#11140d',
        'surface-dim': '#11140d',
        'surface-bright': '#373a32',
        'surface-container-lowest': '#0c0f08',
        'surface-container-low': '#191d15',
        'surface-container': '#1d2119',
        'surface-container-high': '#282b23',
        'surface-container-highest': '#33362d',
        'surface-variant': '#33362d',
        'on-surface': '#e1e4d7',
        'on-surface-variant': '#c2c9b6',
        'inverse-surface': '#e1e4d7',
        'inverse-on-surface': '#2e3229',
        'outline': '#8c9381',
        'outline-variant': '#42493a',
        'surface-tint': '#9fd668',
        'primary': '#9fd668',
        'on-primary': '#1c3700',
        'primary-container': '#81b64c',
        'on-primary-container': '#244400',
        'inverse-primary': '#3b6a00',
        'primary-fixed': '#baf381',
        'primary-fixed-dim': '#9fd668',
        'on-primary-fixed': '#0e2000',
        'on-primary-fixed-variant': '#2b5000',
        'secondary': '#b0d18b',
        'on-secondary': '#1e3702',
        'secondary-container': '#344e17',
        'on-secondary-container': '#9fbf7c',
        'secondary-fixed': '#cceda5',
        'secondary-fixed-dim': '#b0d18b',
        'on-secondary-fixed': '#0f2000',
        'on-secondary-fixed-variant': '#344e17',
        'tertiary': '#ffade6',
        'on-tertiary': '#5d0450',
        'tertiary-container': '#ea84cf',
        'on-tertiary-container': '#6c165d',
        'tertiary-fixed': '#ffd7ef',
        'tertiary-fixed-dim': '#ffade6',
        'on-tertiary-fixed': '#3a0031',
        'on-tertiary-fixed-variant': '#792268',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-background': '#e1e4d7',
        'surface-board-dark': '#779556',
        'surface-board-light': '#ebecd0',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.25rem',
        'md': '0.5rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '16px',
        'unit': '4px',
        'margin': '24px',
        'container-max': '1200px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      animation: {
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.4s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
